# -*- coding: utf-8 -*-
"""deliverable 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0ij6MeZDcz8lLNYYtspC7TPLYQ30FfY
"""

def fibonacciSequence(n):
# returns fib sequence
    if n == 0:
        fibonacciSequence = []
    elif n == 1:
        fibonacciSequence = [0]
    elif n == 2:
        fibonacciSequence = [0, 1]
    elif n > 2:
        fibonacciSequence = [0, 1]
        for i in range(n-2):
            fibonacciSequence += [0]
            fibonacciSequence[-1] = fibonacciSequence[-2] + fibonacciSequence[-3]
    return fibonacciSequence



if __name__ == "__main__":
    n = int(input("Please enter nonegative n: "))
    fibeven = [None] * n
    fibodd = [None] * n
    nSequence = list(range(0,n))
    print(nSequence)
    arr = fibonacciSequence(n)
    print(fibonacciSequence(n))
    for i in range(0,n):
        if(arr[i] % 2 == 0):
            fibeven[i] = arr[i]
        else:
            fibodd[i] = arr[i]
    print(fibeven)
    print(fibodd)